build:
	pandoc --filter pandoc-citeproc --bibliography=privacy_preserving_dht.bib --variable classoption=twocolumn --variable papersize=a4paper privacy_preserving_dht.md -o privacy_preserving_dht.pdf
