build:
	pandoc --filter pandoc-citeproc --bibliography=privacy_vulnerabilities_dht.bib --variable classoption=twocolumn --variable papersize=a4paper privacy_vulnerabilities_dht.md -o privacy_vulnerabilities_dht.pdf
